# Generated by Django 2.1.4 on 2019-09-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20190913_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='token',
        ),
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
